[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  SKIP_PREFLIGHT_CHECK = "true"
  DISABLE_ESLINT_PLUGIN = "true"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
